a2lix_translation_form:
  locale_provider: default       # [1]
  locales: [uk, ru, en]      # [1-a]
  default_locale: en             # [1-b]
  required_locales: [uk]         # [1-c]
  templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"      # [2]