#POST http://127.0.0.1:8000/api/v1/new-lead
POST https://cpa-bond.com/api/v1/new-lead
Content-Type: application/json
Accept: application/json
Authorization: Bearer a66a3730add6f9c22f347abdfd87f006

{
  "stream_id": "612399e8e21b0",
  "name": "Сергей",
  "phone": "0978530430",
  "geo": "UA",
  "ip": "213.225.36.247"
}