POST https://cpa-bond.com/api/v1/new-lead
#POST http://127.0.0.1:8000/api/v1/new-lead
Content-Type: application/json
Accept: application/json
Authorization: Bearer a66a3730add6f9c22f347abdfd87f006

{
  "stream_id": "617a83094c749",
  "name": "Сергей",
  "phone": "097444445444",
  "geo": "UA",
  "ip": "213.225.36.246",
  "referer": "https://google.com/?gclid=Cj0KCQjwm9yJBhDTARIsABKIcGaupN44j1-zdwqYEE_J2-NPtW9qpeV2AmVSejml0E97-f345N8WF58dAmUwEALw_wcB"
}